import * as crypto from "crypto";
const PKG=/^sha256:[0-9a-f]{64}$/;const HEX=/^[0-9a-f]{64}$/;
const EFFECT_RISK:Record<string,number>={READ_ONLY:0,PURE:0,RUNTIME_CONFIGURATION:2,DOCUMENT_MUTATION:3,EXTERNAL_WORLD_CONTACT:4,DELIVERY:5};
function canonical(v:any):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return "["+v.map(canonical).join(",")+"]";return "{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canonical(v[k])).join(",")+"}"}
function sha(v:any){return crypto.createHash("sha256").update(canonical(v)).digest("hex")}
function id(v:any,l:string){const s=String(v||"");if(!/^[A-Za-z0-9][A-Za-z0-9._:/@+-]{0,255}$/.test(s))throw new Error("invalid "+l);return s}
function hex(v:any,l:string){const s=String(v||"");if(!HEX.test(s))throw new Error("invalid "+l);return s}
function pkg(v:any,l:string){const s=String(v||"");if(!PKG.test(s))throw new Error("invalid "+l);return s}
function effect(v:any){const s=String(v||"");if(!(s in EFFECT_RISK))throw new Error("invalid effect");return s}
function normalizeRecord(raw:any){if(!raw||typeof raw!=="object")throw new Error("package record must be object");const package_id=pkg(raw.package_id,"package_id"),extension_id=id(raw.extension_id,"extension_id"),version=String(raw.version||"");if(!/^\d+(\.\d+){0,2}$/.test(version))throw new Error("invalid version");const certificate_sha256=hex(raw.certificate_sha256,"certificate_sha256");const dependencies=(Array.isArray(raw.dependencies)?raw.dependencies:[]).map((d:any)=>({package_id:pkg(d.package_id,"dependency package_id"),extension_id:id(d.extension_id,"dependency extension_id"),version:(()=>{const v=String(d.version||"");if(!/^\\d+(\\.\\d+){0,2}$/.test(v))throw new Error("invalid dependency version");return v})()})).sort((a:any,b:any)=>a.extension_id.localeCompare(b.extension_id)||a.package_id.localeCompare(b.package_id));const capabilities=(Array.isArray(raw.capabilities)?raw.capabilities:[]).map((c:any)=>({name:id(c.name,"capability name"),version:String(c.version||""),effect:effect(c.effect),adapter:id(c.adapter||"UNSPECIFIED","capability adapter"),deterministic:c.deterministic===true})).sort((a:any,b:any)=>a.name.localeCompare(b.name));const tools=(Array.isArray(raw.tools)?raw.tools:[]).map((t:any)=>({name:id(t.name,"tool name"),effect:effect(t.effect)})).sort((a:any,b:any)=>a.name.localeCompare(b.name));return{package_id,extension_id,version,certificate_sha256,dependencies,capabilities,tools}}
export function analyzeComposition(input:any){if(!input||input.schema!=="chatgpt-web-hwpx-mcp/p3.49/composition-request/v1")throw new Error("invalid P3.49 composition request");const records=(Array.isArray(input.packages)?input.packages:[]).map(normalizeRecord);if(records.length<1||records.length>32)throw new Error("composition requires 1..32 packages");const byPkg=new Map(records.map((x:any)=>[x.package_id,x]));if(byPkg.size!==records.length)throw new Error("duplicate package_id");const byExt=new Map<string,any>();for(const r of records){if(byExt.has(r.extension_id))throw new Error("duplicate extension_id");byExt.set(r.extension_id,r)}const conflicts:any[]=[],edges:any[]=[];for(const r of records)for(const d of r.dependencies){const target=byPkg.get(d.package_id);if(!target){conflicts.push({type:"MISSING_DEPENDENCY",packages:[r.package_id,d.package_id],detail:d});continue}if(target.extension_id!==d.extension_id||target.version!==d.version)conflicts.push({type:"DEPENDENCY_IDENTITY_MISMATCH",packages:[r.package_id,d.package_id],detail:d});edges.push({from:d.package_id,to:r.package_id,type:"DEPENDENCY"})}
const visiting=new Set<string>(),visited=new Set<string>(),topo:string[]=[];let cycle:string[]=[];const walk=(p:string,path:string[])=>{if(cycle.length)return;if(visiting.has(p)){cycle=[...path,p];return}if(visited.has(p))return;visiting.add(p);const rec=byPkg.get(p);for(const d of rec.dependencies)if(byPkg.has(d.package_id))walk(d.package_id,[...path,p]);visiting.delete(p);visited.add(p);topo.push(p)};for(const p of [...byPkg.keys()].sort())walk(p,[]);if(cycle.length)conflicts.push({type:"DEPENDENCY_CYCLE",packages:cycle});
const capOwner=new Map<string,string>(),toolOwner=new Map<string,string>();for(const r of records){for(const c of r.capabilities){const prior=capOwner.get(c.name);if(prior&&prior!==r.package_id)conflicts.push({type:"CAPABILITY_PROVIDER_COLLISION",packages:[prior,r.package_id],detail:{capability:c.name}});else capOwner.set(c.name,r.package_id)}for(const t of r.tools){const prior=toolOwner.get(t.name);if(prior&&prior!==r.package_id)conflicts.push({type:"TOOL_NAME_COLLISION",packages:[prior,r.package_id],detail:{tool:t.name}});else toolOwner.set(t.name,r.package_id)}}
const serial=(Array.isArray(input.serial_order)?input.serial_order:[]).map((x:any)=>pkg(x,"serial_order package"));if(serial.length!==records.length||new Set(serial).size!==records.length||serial.some((x:string)=>!byPkg.has(x)))conflicts.push({type:"INVALID_SERIAL_ORDER",packages:serial});const pos=new Map(serial.map((x:string,i:number)=>[x,i]));for(const e of edges)if(pos.has(e.from)&&pos.has(e.to)&&(pos.get(e.from) as number)>(pos.get(e.to) as number))conflicts.push({type:"DEPENDENCY_ORDER_VIOLATION",packages:[e.from,e.to]});
const maxEffect=effect(input.max_effect||"DELIVERY"),maxRisk=EFFECT_RISK[maxEffect];for(const r of records)for(const c of r.capabilities)if(EFFECT_RISK[c.effect]>maxRisk)conflicts.push({type:"EFFECT_BUDGET_EXCEEDED",packages:[r.package_id],detail:{capability:c.name,effect:c.effect,max_effect:maxEffect}});for(const r of records)for(const t of r.tools)if(EFFECT_RISK[t.effect]>maxRisk)conflicts.push({type:"EFFECT_BUDGET_EXCEEDED",packages:[r.package_id],detail:{tool:t.name,effect:t.effect,max_effect:maxEffect}});
const serialWitnesses:any[]=[];for(let i=0;i<records.length;i++)for(let j=i+1;j<records.length;j++){const a=records[i],b=records[j],ar=Math.max(-1,...a.capabilities.map((c:any)=>EFFECT_RISK[c.effect]),...a.tools.map((t:any)=>EFFECT_RISK[t.effect])),br=Math.max(-1,...b.capabilities.map((c:any)=>EFFECT_RISK[c.effect]),...b.tools.map((t:any)=>EFFECT_RISK[t.effect]));if(ar>=3&&br>=3){const ordered=pos.has(a.package_id)&&pos.has(b.package_id);if(!ordered)conflicts.push({type:"NONCOMMUTATIVE_PAIR_UNORDERED",packages:[a.package_id,b.package_id]});else serialWitnesses.push({packages:[a.package_id,b.package_id],order:(pos.get(a.package_id) as number)<(pos.get(b.package_id) as number)?[a.package_id,b.package_id]:[b.package_id,a.package_id],reason:"MUTATING_OR_EXTERNAL_PAIR_SERIALIZED"})}}
const environment={p347_registry_generation:Number(input.environment?.p347_registry_generation||0),trust_policy_sha256:hex(input.environment?.trust_policy_sha256,"trust_policy_sha256"),p346_adapter_generation:Number(input.environment?.p346_adapter_generation||0),p346_adapter_contract_sha256:hex(input.environment?.p346_adapter_contract_sha256,"p346_adapter_contract_sha256"),joint_host_conformance_sha256:hex(input.environment?.joint_host_conformance_sha256,"joint_host_conformance_sha256")};if(!Number.isInteger(environment.p347_registry_generation)||environment.p347_registry_generation<1)throw new Error("invalid p347 registry generation");if(!Number.isInteger(environment.p346_adapter_generation)||environment.p346_adapter_generation<1)throw new Error("invalid p346 adapter generation");
const normalized={schema:"chatgpt-web-hwpx-mcp/p3.49/composition-manifest/v1",packages:records.map((r:any)=>({package_id:r.package_id,extension_id:r.extension_id,version:r.version,certificate_sha256:r.certificate_sha256})).sort((a:any,b:any)=>a.extension_id.localeCompare(b.extension_id)),dependency_edges:edges.sort((a:any,b:any)=>a.from.localeCompare(b.from)||a.to.localeCompare(b.to)),topological_order:topo,serial_order:serial,max_effect:maxEffect,environment};const status=conflicts.length===0?"PASS":"FAIL",minimalCulprit=[...new Set(conflicts.flatMap((x:any)=>x.packages||[]))].sort(),composition_sha256=sha(normalized);return{...normalized,status,conflicts,conflict_count:conflicts.length,minimal_culpable_packages:minimalCulprit,noncommutative_serialization:serialWitnesses,composition_id:"sha256:"+composition_sha256,composition_sha256,authority:status==="PASS"?"P349_JOINT_COMPOSITION_ANALYSIS_PASS":"P349_JOINT_COMPOSITION_ANALYSIS_FAIL"}}
export const P349_COMPOSITION_CONTRACT={schema:"chatgpt-web-hwpx-mcp/p3.49/composition-contract/v1",phase:"P3.49",product:"0.26.0-p3.49",max_packages:32,package_authority:"P3.47_PROMOTED_CERTIFIED_PACKAGES_ONLY",environment_authority:"P3.46_ACTIVE_ADAPTER_PROFILE_PLUS_P3.47_TRUST_POLICY",joint_host_evidence:"P3.47_SIGNED_DIFFERENTIAL_HOST_OBSERVATIONS_REUSED_AT_COMPOSITION_SCOPE",activation:"OWNER_SCOPED_COMPOSITION_POINTER_CAS",rollback:"EXACT_PRIOR_CERTIFIED_COMPOSITION_POINTER_ONLY",component_certification_does_not_imply_composition_safety:true,arbitrary_dynamic_loading:false};export function compositionContract(){return JSON.parse(JSON.stringify(P349_COMPOSITION_CONTRACT))}
