const fs=require("fs"),cp=require("child_process");
const rt=require("../.tmp/p345-ts/contracts/p345_runtime.js");
const ir=JSON.parse(fs.readFileSync("benchmarks/p345_runtime_fixture.json","utf8"));
const compiled=rt.compileAuthoringIR({ir});
if(compiled.actions.snapshot!=="EXECUTE"||compiled.actions.format!=="EXECUTE"||compiled.actions.render!=="WAIT_EXTERNAL")throw new Error("unexpected initial plan");
let state=rt.createRun(compiled);
state=rt.transitionRuntime({state,command:{type:"START_NODE",node_id:"snapshot"}});
state=rt.transitionRuntime({state,command:{type:"COMMIT_NODE",node_id:"snapshot",revision:1,output_sha256:"a".repeat(64),receipt_sha256:"1".repeat(64)}});
state=rt.transitionRuntime({state,command:{type:"START_NODE",node_id:"format"}});
state=rt.transitionRuntime({state,command:{type:"COMMIT_NODE",node_id:"format",revision:2,output_sha256:"b".repeat(64),receipt_sha256:"2".repeat(64)}});
state=rt.transitionRuntime({state,command:{type:"WAIT_NODE",node_id:"render"}});
state=rt.transitionRuntime({state,command:{type:"RESOLVE_NODE",node_id:"render",output_sha256:"c".repeat(64),receipt_sha256:"3".repeat(64)}});
state=rt.transitionRuntime({state,command:{type:"COMPLETE_RUN"}});
const replay=JSON.parse(cp.execFileSync(process.env.P345_REPLAY_BIN||"p345-replay",["verify"],{input:JSON.stringify(state),encoding:"utf8"}));
if(!replay.ok||!replay.completed||replay.head_event_hash!==state.head_event_hash)throw new Error("Rust replay mismatch");
const prior={snapshot:{node_spec_sha256:compiled.node_spec_sha256.snapshot,provider_binding_sha256:rt.sha256(compiled.provider_bindings.snapshot),output_sha256:"a".repeat(64),terminal_state:"COMMITTED"}};
const recompiled=rt.compileAuthoringIR({ir,prior_snapshot:prior});
if(recompiled.actions.snapshot!=="REUSE")throw new Error("pure snapshot should reuse");
if(recompiled.actions.format!=="EXECUTE"||recompiled.actions.render!=="WAIT_EXTERNAL")throw new Error("side effects must not reuse");
const changed=rt.compileAuthoringIR({ir,prior_snapshot:prior,changed_node_ids:["snapshot"]});
if(!changed.affected_nodes.includes("format")||!changed.affected_nodes.includes("render"))throw new Error("transitive invalidation failed");
const obs=rt.observability(state);if(obs.event_count!==8||obs.committed_nodes!==3)throw new Error("observability mismatch");
console.log(JSON.stringify({status:"PASS",events:state.events.length,head:state.head_event_hash,affected:changed.affected_nodes}));
